export const KEY_APP_NAVIGATOR = 'appNavigator';

export default navigationString = {
  TodoScreen: 'todoScreen',
  ChatScreen: 'chatScreen',
  UserScreen: 'userScreen',
  DrawerBar: 'drawerBar',
  MessageScreen: 'messageScreen',
  LoginScreen: 'loginScreen',
  ContactScreen: 'contactScreen',
  InitialScreen: 'initialScreen',
  FormScreen: 'formScreen',
  TeamScreen: 'teamScreen',
  TemplatesScreen: 'templatsScreen',
  GroupsScreen: 'groupsScreen',
  TaskScreen: 'taskScreen',
  FormResponseCompleteScreen: 'formResponseCompleteScreen',
  FormResponseInCompleteScreen: 'formResponseInCompleteScreen',
  TaskResponseScreen: 'taskResponseScreen',
  ContactListDetailsRowScreen: 'contactListDetailsRowScreen',
  LocalContactListScreen: 'localContactListScreen',
  BottomSheetNavigateComp: 'bottomSheetNavigateComp',
  CreateTask: 'createTask',
  RepeatTask: 'repeatTask',
  RepeatTaskComponent: 'repeatTaskComponent',
  CreateTaskComponent: 'CreateTaskComponent',
  DashBordScreen: 'dashBordScreen',
  TaskCommentComponent: 'taskCommentComponent',
  searchContact: 'searchContact',
  searchMessage: 'searchMessage',
  splashScreen: 'splashScreen',
  broadCastGroupScreen: 'broadCastGroupScreen',
  broadCastMessageScreen: 'broadCastMessageScreen',
  broadCastGroupDetailScreen: 'broadCastGroupDetailScreen',
  BroadCastGroupMessageListColumScreen: 'broadCastGroupMessageListColumScreen',
  BroadCastGroupMessageConatctDetailsScreen: 'broadCastGroupMessageConatctDetailsScreen',
  BroadCastGroupSearchContactScreen: 'broadCastGroupSearchContactScreen',
  ProjectScreen: 'projectScreen',
  ComplainsScreen: 'complainsScreen',
  FeedBackScreen: 'feedBackScreen',
  CommonComplaitsAndFeedBack: 'commonComplaitsAndFeedBack',
  webView:'webView',
  Support:'SupportScreen',
  PrivacyPolicy:'PrivacyPolicy',
  AnniversaryScreen:'anniversaryScreen'
};
